fix: newK3sOrb uses cilium as CNI now

diff --git a/home/dot_omz_custom/aliases.zsh.tmpl b/home/dot_omz_custom/aliases.zsh.tmpl
--- a/home/dot_omz_custom/aliases.zsh.tmpl
+++ b/home/dot_omz_custom/aliases.zsh.tmpl
@@ -10,13 +10,11 @@ function newK3sOrb() {
     echo "Missing name parameter or having too many parameters"
     exit 1
   fi
-  orbctl create ubuntu $1 
-  if [ command -v k3sup ]; then
-    echo "k3sup not installed"
-    orbctl delete $1
-    exit 1
-  fi
 
+  # Create VM
+  orbctl create ubuntu $1 
+
+  # Setup Cluster
   k3sup install \
     --cluster \
     --host localhost \
@@ -28,14 +26,40 @@ function newK3sOrb() {
     --ssh-port 32222 \
     --sudo \
     --tls-san $1.orb.local \
-    --k3s-extra-args="--cluster-domain=$1.local"  
+    --k3s-extra-args='--disable=traefik --flannel-backend=none --disable-network-policy'  
+
+  if [ $? -ne 0 ]; then
+    echo "error during k3s bootstrap"
+    orbctl delete $1 -f
+    exit 1
+  fi
 
   # Replace the server-url in the kubeconfig with the remote cluster
   kubectl config set-cluster $1 --server=https://$1.orb.local:6443
+
+  # The CIDR is the default in K3s
+  # some settings have been taken from a "cilium install" magic detection
+  # port 1025 is taken since it's lower than 6443 so that orb's proxy uses this as backend port
+  kubectl config use-context $1
+  helm upgrade -i cilium cilium -n kube-system --repo https://helm.cilium.io \
+    --set="ingressController.enabled=true" \
+    --set="ingressController.hostNetwork.enabled=true" \
+    --set="ingressController.hostNetwork.sharedListenerPort=1025" \
+    --set="ingressController.loadBalancerMode=shared" \
+    --set="ipam.operator.clusterPoolIPv4PodCIDRList=10.42.0.0/16" \
+    --set="hubble.ui.enabled=true" \
+    --set="hubble.relay.enabled=true" \
+    --set="k8sServiceHost=127.0.0.1"\
+    --set="k8sServicePort=6443" \
+    --set="kubeProxyReplacement=true" \
+    --set="operator.replicas=1" \
+    --set="routingMode=tunnel" \
+    --set="tunnelProtocol=vxlan"
+
 }
 
 function deleteK3sOrb() {
-  orbctl delete $1
+  orbctl delete $1 -f
   kubectl config delete-cluster $1
   kubectl config delete-context $1
   kubectl config delete-user $1
